---
Name: approutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "api/v1/warna//$Action/$ID": WarnaController
    "api/v1/product//$Action/$ID": ProductController
