---
Name: approutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "api/v1/auth//$Action/$ID": AuthController
    "api/v1/dashboard": DashboardController
    "api/v1/warna//$Action/$ID": WarnaController
    "api/v1/product//$Action/$ID": ProductController
    "api/v1/pembelian//$Action/$ID": PembelianProductController
